import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { Providers } from './provider'
import './globals.css'

import { Navbar, NavbarBrand, NavbarContent, NavbarItem, Button } from '@nextui-org/react'
import { IconBrandGithub, IconSun } from '@tabler/icons-react'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className='light'>
      <body className={inter.className}>
          <Navbar>
            <NavbarBrand>
              .photocave
            </NavbarBrand>
            <NavbarContent className='justify-end'>
              <NavbarItem className='ml-auto'>
                <Button radius='full' isIconOnly aria-label='Go to github' variant='light'><IconBrandGithub></IconBrandGithub></Button>
              </NavbarItem>
              <NavbarItem>
                <Button radius='full' isIconOnly aria-label='Switch theme' variant='light'><IconSun></IconSun></Button>
              </NavbarItem>
            </NavbarContent>
          </Navbar>
          <Providers>
            {children}
          </Providers>
      </body>
    </html>
  )
}
